# Generated by Django 3.1.4 on 2021-01-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210105_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='doctorId',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='patientId',
            new_name='patient',
        ),
    ]
